package dev.oritwig.markup.core;
import android.graphics.*;import java.nio.*;import java.nio.file.*;import java.io.*;import java.util.*;
public final class CoreHostTest {
 static int checks;static void check(boolean value,String name){checks++;if(!value)throw new AssertionError(name);System.out.println("PASS "+name);}
 static boolean eq(double a,double b){return Math.abs(a-b)<.0001;}
 public static void main(String[] args)throws Exception{
  Point p=new Point(3,4,2),q=new Point(6,8,3);check(eq(p.getDistanceTo(q),Math.sqrt(26)),"original Point distance");Point a=p.add(q);check(eq(a.x,9)&&eq(a.y,12)&&eq(a.z,5),"original Point addition");Point b=p.multiplyByScalar(.5);check(eq(b.x,1.5)&&eq(b.y,2)&&eq(b.z,1),"original Point multiplication");
  RenderState state=new RenderState();state.prepare();state.appendValuesCount(3);for(int i=0;i<3;i++)check(state.addPoint(new PointF(i,2*i),3+i,.1f*i,.8f,-1),"RenderState stores stamp "+i);state.setPosition(0);check(eq(state.read(),0)&&eq(state.read(),0)&&eq(state.read(),3),"RenderState stamp vertex fields");state.reset();check(state.getCount()==0&&state.remainder==0,"RenderState reset");
  File dir=Files.createTempDirectory("markup-host-normal-").toFile();byte[] data=new byte[64*32*4];for(int i=0;i<data.length;i++)data[i]=(byte)(i*17);Slice slice=new Slice(ByteBuffer.wrap(data),0,new RectF(7,11,71,43),dir);check(slice.getX()==7&&slice.getY()==11&&slice.getWidth()==64&&slice.getHeight()==32,"original Slice region coordinates");check(dir.list().length==1,"original Slice compressed file exists");check(Arrays.equals(data,slice.getData().array()),"original Slice normal-byte deflate/inflate roundtrip");slice.cleanResources();check(dir.list().length==0,"original Slice cleanup");ByteBuffer direct=ByteBuffer.allocateDirect(data.length);direct.put(data).flip();Slice directSlice=new Slice(direct,0,new RectF(0,0,64,32),dir);check(Arrays.equals(data,directSlice.getData().array()),"Slice direct GL buffer normal-byte roundtrip");check(direct.position()==0,"Slice retains caller buffer position");directSlice.cleanResources();dir.delete();
  UndoStore undo=new UndoStore();StringBuilder ops=new StringBuilder();final int[] changed={0};undo.setDelegate(()->changed[0]++);UUID one=UUID.randomUUID(),two=UUID.randomUUID();undo.registerUndo(one,()->ops.append('1'));undo.registerUndo(two,()->ops.append('2'));check(undo.canUndo(),"UndoStore registration");undo.undo();undo.undo();check(ops.toString().equals("21")&&!undo.canUndo(),"UndoStore real LIFO execution");undo.registerUndo(one,()->ops.append('x'));undo.unregisterUndo(one);undo.undo();check(ops.toString().equals("21"),"UndoStore unregister");undo.registerUndo(one,()->ops.append('3'));undo.registerUndo(two,()->ops.append('4'));undo.clear();check(ops.toString().equals("2143"),"UndoStore clear invokes actual actions");undo.registerUndo(one,()->ops.append('z'));undo.reset();check(!undo.canUndo()&&ops.toString().equals("2143"),"UndoStore reset only discards history");check(changed[0]>=10,"UndoStore notifies history changes");System.out.println("HOST_CHECKS="+checks);
 }
}
